name: Playwright Chromium (Amazon only)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  chromium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: Amazon

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: Amazon

      - name: Run Chromium tests
        run: npx playwright test --project=chromium --grep @smoke
        working-directory: Amazon
