name: Playwright Tests - Firefox (All Except Amazon)

on: [push, pull_request]

jobs:
  firefox-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project-dir: [PetStore, SauceDemo, TodoMVC]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.project-dir }}

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ${{ matrix.project-dir }}

      - name: Run tests on Firefox
        run: npx playwright test --project=firefox
        working-directory: ${{ matrix.project-dir }}
