name: Run Playwright tests

on: [push]

jobs:
  firefox-projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [TodoMVC, PetStore, SauceDemo]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.project }}

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ${{ matrix.project }}

      - name: Run Playwright tests (Firefox)
        run: npx playwright test --project=firefox
        working-directory: ${{ matrix.project }}

  amazon-WebKit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: Amazon

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: Amazon

      - name: Run Playwright tests (WebKit)
        run: npx playwright test --project=WebKit
        working-directory: Amazon
