name: Run Playwright tests

on: [push]

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: TodoMVC

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: TodoMVC

      - name: Run Playwright tests (Firefox on all projects)
        run: npx playwright test --project=firefox
        working-directory: TodoMVC
