name: Run Playwright tests

on: [push, pull_request]

jobs:
  test-firefox:
    name: Playwright - Firefox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: Amazon

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: Amazon

      - name: Run Playwright tests on Firefox
        run: npx playwright test --project=firefox
        working-directory: Amazon

  test-chromium:
    name: Playwright - Chromium
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: Amazon

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: Amazon

      - name: Run Playwright tests on Chromium
        run: npx playwright test --project=chromium
        working-directory: Amazon
