name: Run Playwright tests (Firefox only)

on: [push]

jobs:
  run-firefox-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [TodoMVC, PetStore, Sauce Demo]

    name: Firefox - ${{ matrix.project }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm ci
        working-directory: ${{ matrix.project }}

      - name: Install Playwright + Firefox
        run: npx playwright install --with-deps firefox
        working-directory: ${{ matrix.project }}

      - name: Run Playwright tests (Firefox only)
        run: npx playwright test --project=firefox
        working-directory: ${{ matrix.project }}
